# Generated by Django 5.1.7 on 2025-03-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_payment_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paypal_id',
        ),
    ]
